# Generated by Django 3.1.4 on 2022-01-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20211115_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name_plural': 'Users Follows'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='review_add',
            field=models.BooleanField(default=False),
        ),
    ]
